repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
      - id: autopep8
        additional_dependencies: ['autopep8']

  - repo: https://github.com/pre-commit/mirrors-black
    rev: v23.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.0
    hooks:
      - id: clang-format
        name: Format C/C++ code
        additional_dependencies: ['clang-format']

  - repo: https://github.com/pre-commit/mirrors-shellcheck
    rev: v0.9.0
    hooks:
      - id: shellcheck
        name: Lint Bash scripts
        files: \.sh$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: flake8
        additional_dependencies: ['flake8']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.15.1
    hooks:
      - id: pylint
        additional_dependencies: ['pylint']
